### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by mgcrea** [depoon/NetworkInterceptor#16]
So I'm pretty much very junior to swift related development (did some Obj-C back in the days but a bit rusty too).

I haven't found a way to properly build the example project:

- The `NetworkInterceptor.framework` in Xcode appear to be missing
- What I try to do is to build the framework independently (works) and show build in finder then drag-drop built file into the exemple project (deleting the previous missing ref).

However it won't build anyway as it could not find the module:

```
~/Developer/foobar/ios-inject/NetworkInterceptor/NetworkInterceptorExample/NetworkInterceptorExample/ViewController.swift:10:8: No such module 'NetworkInterceptor'
```

Have a working static injection project (following your tutorial), but as well, I'm stuck properly loading the `CodeInjectionSwift.swift` code, not sure if because it's Swift or if there is as well an issue while loading the built framework (same drag&drop from build).

Would love any insight you could have on this, 

Thanks for the great work! I'm looking to reverse-engineer an home automation app and your code looks like to be my last resort! (SSL certificate pinning).

---

**EDIT**

Tweaking the framework search path it looks like it loads it now but I'm encountering header issues:

<img width="1447" alt="screenshot 2018-10-04 at 16 23 43" src="https://user-images.githubusercontent.com/108273/46480638-e8b4aa00-c7f1-11e8-9da4-75adab78eab9.png">

**Comment by depoon** [comment]
1. Please Open **_NetworkInterceptor.xcworkspace_** instead
2. Build  ** NetworkInterceptor** target
3. Run Example project

How do you wish to reverse engineer that app? I might have an easier solution

**Comment by mgcrea** [comment]
Thanks for the answer! Indeed opening the workspace seems to have fixed the build issues, back to work!

The app I'm trying to reverse is a free home automation app, available both on iOS and Android. Their are quite famous in my country, but their system is totally closed unfortunately.

I was able to debug the initial login handshake that uses some kind of [Digest access authentication](https://en.wikipedia.org/wiki/Digest_access_authentication) but to initiate a WebSocket connection. That part is working fine and I'm properly receiving WebSocket messages from the server (that looks like to be raw HTTP requests).

The big issue is that I don't have a clue what is the proper API (aka. WebSocket message) to trigger stuff (tried a few variations of the received message with no luck).

I've spent a lot of time trying to debug these network frames using [Charles for iOS](https://www.charlesproxy.com/documentation/ios/), then a combination of [mitm-proxy](https://mitmproxy.org/) and [WireShark](https://www.wireshark.org) combined with the use of a [Remote Virtual Interface](https://developer.apple.com/library/archive/qa/qa1176/_index.html).

Big issue is that it looks like WebSocket frames do not use the proxy, were not properly SSL decrypted by Charles, and when I finally was able to force the SSL override the app won't work anymore (due to SSL pining).

So my only hope left was to somehow debug these WebSocket messages before they are sent / encrypted thanks to your work. If you have any other idea (or maybe some other iOS method injection to perform related to WebSocket usage), I'd be more than happy to hear them.

If you are interested, I can send you unencrypted version of both iOS/Android apps!

Thanks again for the help!

**Comment by depoon** [comment]
Drop me an email regarding the unencrypted app pls.
de_poon@hotmail.com

**Comment by mgcrea** [comment]
@depoon done, thanks!

**Comment by depoon** [comment]
On PatchLoader.m, since you are creating a framework, use this import instead 
```ObjC
#import <PatchFramework/PatchFramework-Swift.h>
```

In CodeInjectionSwift you need to declare your class and func public in order to use them

**Comment by mgcrea** [comment]
Thanks, it did indeed fixed build issues.

Unfortunately it looks like I've hit another deadend, I can't import the required Swift dylibs as they crash (due to missing symbols), eg:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Symbol not found: _$SSJN | Referenced from: /var/containers/Bundle/Application/7739779D-14CF-4DFD-AF21-4BF6B6E9617C/Tydom.app/Dylibs/libswiftSwiftOnoneSupport.dylib | Expected in: /private/var/containers/Bundle/Application/7739779D-14CF-4DFD-AF21-4BF6B6E9617C/Tydom.app/Frameworks/libswiftCore.dylib | in /var/containers/Bundle/Application/7739779D-14CF-4DFD-AF21-4BF6B6E9617C/Tydom.app/Dylibs/libswiftSwiftOnoneSupport.dylib
```

Probably because either XCode is too recent (and device is in 10.3) or maybe the fact that it is 32-bit.

**Comment by oli06** [comment]
Hi @mgcrea,

Not sure, if I'm on the right way understanding your issue. But I also got into trouble using the required (or not required) Swift dylibs while experimenting with CodeInjection.

First I used all the default Swift dylibs (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift), but soon found out, that the easiest way of using only the required dylibs is to build your framework, open it in finder and copy all dylibs from the /Frameworks directory.

Especially for libswiftSwiftOnoneSupport.dylib, this was only required if I wanted to use a debug version of the framework on my iOS-device. Otherwise this dylib is not required (and shouldn't therefore not be included).

**Comment by mgcrea** [comment]
Indeed it looks like I was building it in debug mode. Had been able to get a 64-bit device and wanted to try again but I'm not sure if an Xcode update broke something but I get:

```
dyld: Library not loaded: @rpath/NetworkInterceptor.framework/NetworkInterceptor
  Referenced from: /var/containers/Bundle/Application/96A22878-6F2A-4670-99ED-268CF907F9D2/NetworkInterceptorExample.app/NetworkInterceptorExample
  Reason: image not found
```

When trying to run the example. I've opened the workspace and built the NetworkInterceptor target first. Any ideas?

**Comment by mgcrea** [comment]
Finally made it work today!! had to compile my framework with Xcode 9 (still downloadable on Apple developer) to be on the same SDK than the app.

However I'm receiving truncated body/content in the console, is it normal @depoon?

```
default	01:07:35.829411 +0100	Tydom	Task <157440F7-FB34-41CC-A208-968EB2C32118>.<0> sent request, body N
default	01:07:35.838641 +0100	Tydom	Task <157440F7-FB34-41CC-A208-968EB2C32118>.<0> received response, status 401 content U
```

Anyway I guess I can close this!
