### ISSUE TITLE
install issue.

### ISSUE THREAD

**Issue by gaplan** [depoon/NetworkInterceptor#19]
when I try this command,
pod 'NetworkInterceptor', : git => 'https://github.com/depoon/NetworkInterceptor.git', :tag => '0.0.5'

I see this error;

-bash: https://github.com/depoon/NetworkInterceptor.git,: No such file or directory

**Comment by gaplan** [comment]
Or if i use pod install

this is the error message;

[!] The Podfile contains framework or static library targets (NetworkInterceptor), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).

**Comment by depoon** [comment]
Hey sorry for the late reply. I have published the pod to cocoapods and its now 0.0.8.

Let me know if you still encoutering issues

**Comment by depoon** [comment]
Have you tried with the latest version?

**Comment by gaplan** [comment]
Sorry for delay.

pod --version 1.5.3
MacOs 10.13.6

pod 'NetworkInterceptor'
[!] Unknown command: `NetworkInterceptor`
Did you mean: deintegrate?

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

**Comment by depoon** [comment]
Refer to this
https://github.com/depoon/ios-movies-app/blob/master/Podfile

You need to create a Podfile which describes all the required dependencies of your project.

Then you all you need to run `pod install`

**Comment by depoon** [comment]
can u msg me your github repo? maybe let me create a PR commit for you
