### ISSUE TITLE
NetworkInterceptor example file.

### ISSUE THREAD

**Issue by gaplan** [depoon/NetworkInterceptor#23]
When i try NetworkInterceptorexample file. 
this is my error message.

dyld: Library not loaded: @rpath/NetworkInterceptor.framework/NetworkInterceptor
  Referenced from: /var/containers/Bundle/Application/69C104C8-576C-4D50-8396-8B4146AFACC8/NetworkInterceptorExample.app/NetworkInterceptorExample
  Reason: image not found

**Comment by gaplan** [comment]
Update ;
Xcode Version 10.2.1 (10E1001)

**Comment by depoon** [comment]
You need to embed the framework in the app target. Missing this, xcode will not issue a compile time error.

**Comment by gaplan** [comment]
i'm ok , i can do now.
thank for the code
